### ISSUE TITLE
TLC output parser fails for counterexamples of length 1

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator-py#55]
The TLC output when the invariant is violated already in the initial state (such as [this one](https://github.com/informalsystems/modelator-py/blob/ivan/parsingTlcOut/tests/resource/TlcTraceParseInitState.txt)) will not be parsed correctly by [itf.py](https://github.com/informalsystems/modelator-py/blob/ivan/parsingTlcOut/modelator_py/util/tlc/itf.py). 

The problem is in trying to match the exact output (which was taken from traces with more states), [here](https://github.com/informalsystems/modelator-py/blob/38b0d43595627b160a915dd9920d80e92587c023/modelator_py/util/tlc/stdout_to_informal_trace_format.py#L37)

**Comment by danwt** [comment]
Hey, sorry about this, there are a ton of cases and I didn't get this one! LMK if you'd like my input, althought seems like you've got it figured out.

**Comment by danwt** [comment]
By the way, there is another location to get traces, from the 'TTrace' files that TLC outputs. Just FYI. (I wish I'd done it that way, in retrospect).

**Comment by ivan-gavran** [comment]
Thanks for that comment, I'll see if it perhaps makes more sense to use the TTrase file

**Comment by danwt** [comment]
Cool. I'd say it's most likely not worth the effort if this is the 'last' bug in the current impl.

**Comment by ivan-gavran** [comment]
Hey, @danwt : in what cases (for which command) will TLC generate multiple traces? (I see that the function is built to support this, but I do not know how to get multiple traces)

As a side note: for the trace of length 1, the 'TTrace' is not generated.

**Comment by danwt** [comment]
> As a side note: for the trace of length 1, the 'TTrace' is not generated.

hehe that's amazing.

> in what cases (for which command) will TLC generate multiple traces?

If you pass `-continue`! (And if there _are_ multiple possible traces)

**Comment by danwt** [comment]
It doesn't stop! Maybe there is a special TLC operator you could put in the spec to get some behavior like that, like what Igor mentioned the other day, but I've never used such a thing.

**Comment by danwt** [comment]
I think literally the only thing `continue` does is it sets some flag. So TLC probably has some code like
```
while(!invariantBroken() || continue){
 bfsStep()
 checkInvariant()
}
```
