### ISSUE TITLE
Bump versions in `pyproject.toml`

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/modelator-py#59]
python to 3.10
pytest to 7.1.2

**Comment by danwt** [comment]
I chose 3.9.9 instead of 3.10 for a specific reason, but I can't remember! Who knows, maybe it's no longer a problem.

**Comment by danwt** [comment]
I think it was to do with the multiprocessing library breaking in 3.10

**Comment by rnbguy** [comment]
:smile: thanks @danwt we now offer minimum support since 3.8.x.
